# Generated by Django 3.2.6 on 2021-08-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=200, unique=True)),
                ('City', models.CharField(max_length=200)),
                ('Price', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Bed', models.CharField(max_length=2)),
                ('Bath', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
